# Generated by Django 2.1.1 on 2018-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('terreno', models.CharField(max_length=20)),
                ('cuartos', models.CharField(max_length=20)),
                ('banos', models.CharField(max_length=20)),
            ],
        ),
    ]
