# Generated by Django 2.1.1 on 2018-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='precio',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedades',
            name='ubicacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
