# Generated by Django 2.1.1 on 2018-11-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20181116_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedades',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='propiedades',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='tipo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
