# Generated by Django 2.1.1 on 2018-11-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20181116_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='slug',
            field=models.SlugField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
