# Generated by Django 2.1.1 on 2018-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_propiedades_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='venta', max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='tipo',
            field=models.CharField(choices=[('venta', 'VENTA'), ('renta', 'RENTA')], default='activo', max_length=10),
        ),
    ]
