# Generated by Django 2.1.1 on 2018-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20181121_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='descripcion',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
